services:

  redis:
    image: redis:7-alpine

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0

  kafka:
    image: confluentinc/cp-kafka:7.6.0

  postgres:
    image: postgres:17-alpine

  cleanarchitecture-api:
    image: ${DOCKER_REGISTRY-}cleanarchitecture-api:latest
    build:
      context: .
      dockerfile: CleanArchitecture.API/Dockerfile

  cleanarchitecture-jobs:
    image: ${DOCKER_REGISTRY-}cleanarchitecture-jobs:latest
    build:
      context: .
      dockerfile: CleanArchitecture.Jobs/Dockerfile

volumes:
  postgres_data: {}
  redis_data: {}
  zookeeper_data: {}
  kafka_data: {}
